// Actions
export const GAME_REQUEST = "GAME_REQUEST";
export const GAME_REQUEST_FULFILLED = "GAME_REQUEST_FULFILLED";
export const LEAVE_ROOM = "LEAVE_ROOM";
export const DISCONNECTED = "DISCONNECTED";

export const TTT_INIT_MATCH = "TTT_INIT_MATCH";
export const TTT_SEND_MOVE = "TTT_SEND_MOVE";
export const TTT_GAME_MOVE_RESPONSE = "TTT_GAME_MOVE_RESPONSE";

export const DOTS_INIT_MATCH = "DOTS_INIT_MATCH";
export const DOTS_SEND_MOVE = "DOTS_SEND_MOVE";
export const DOTS_GAME_MOVE_RESPONSE = "DOTS_GAME_MOVE_RESPONSE";
